---
title: "AutonomousRacingResults"
author: "Benjamin Evans"
date: "04/02/2022"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

data = read.csv("DataTable.csv")

library(ggplot2)
library(dplyr)
library(tidyr)
library(knitr)

```

# Kernel Safety Tests

Firstly, we run random tests to ensure that the kernels are safe and that they do work.

```{r, kernel_safety}
kernel_gen = data %>%
  filter(eval_name=="KernelGen")%>%
  select(map_name, SSS_avg_interventions, SSS_avg_times, SSS_std_dev, SSS_success_rate)
  
kable(kernel_gen)
```

# Learning Investigation

```{r}
reward = data %>%
  filter(eval_name=="RewardTest") %>%
  select(agent_name, rk, constant_reward, SSS_avg_times, SSS_std_dev,  SSS_avg_interventions)%>%
     arrange(agent_name)


kable(reward)
```


# Training Comparision

## Performance
```{r}

benchmarks = data %>%
  filter(eval_name=="repeat")%>%
  # filter(Wo_avg_times> 1)%>%
  select(agent_name, SSS_avg_times, Wo_avg_times, Wo_success_rate)%>%
   arrange(desc(agent_name))

kable(benchmarks)


```

## Stability
```{r, stability}

data %>%
  filter(eval_name=="repeat")%>%
  filter(Wo_avg_times>6)%>%
  select(agent_name, Wo_avg_times, Wo_success_rate, vehicle)%>%
  ggplot(aes(x=vehicle, y=Wo_avg_times, group=vehicle))+
  geom_boxplot()
  # coord_cartesian(ylim = c(1, 20))

b =  data %>%
  filter(eval_name=="repeat")%>%
  filter(Wo_avg_times>6)%>%
  select(Wo_avg_times, vehicle, agent_name)%>%
  pivot_wider(names_from = vehicle, values_from = Wo_avg_times)
  # group_by(vehicle)
  
summary(b)
```


# Benchmarking


```{r}

benchmarks = data %>%
  filter(eval_name=="benchmark")%>%
  select(vehicle, map_name, Wo_avg_times, Wo_std_dev)%>%
   arrange(desc(vehicle)) %>%
  pivot_wider(names_from = map_name, values_from = c(Wo_avg_times, Wo_std_dev))

#TODO: get map name then use pivot wider to compare accross maps.

kable(benchmarks)

```



