# map
# map_name: "porto"
map_name: "columbia_small"
# map_name: "f1_aut_wide"
map_ext: ".png"
sx: 0.0
sy: 0
# stheta: -0.4  # porto
stheta: 0  # columbia, f1 aut

max_v: 3
max_a: 8.5
max_steer: 0.4
max_d_dot: 3.2
mu: 0.523
m: 3.47
g: 9.81
l_r: 0.171
l_f: 0.158

# agent parameters
n_beams: 20
range_finder_scale: 5
h_size: 100
r1: 0.08
r2: 0.001
rk: 0.0


#simulator
sim_steps: 5
max_steps: 1000

# PP
lookahead: 0.82
v_gain: 0.9
v_min_plan: 1

# test params
test_n: 10
train_n: 120000

#save_paths
vehicle_path: "Data/Vehicles/"

